### ISSUE TITLE
/log stores several timestamps

### ISSUE THREAD

**Issue by AitorF** [DITAS-Project/VDC-Logging-Agent#11]
`/log` endpoint stores 3 timestamps:

* `@timestamp` whith the value of the record insertion, I guess. Ok.
* `timestamp` *What is this field needed for*?
* `value.timestamp` The API requests a `timestamp` field too, I guess with the exact moment of the log. Ok.

![image](https://user-images.githubusercontent.com/2410661/52268141-0aa67080-293b-11e9-9b8d-5113c396fbea.png)

API definition file:
![image](https://user-images.githubusercontent.com/2410661/52268298-78529c80-293b-11e9-9bc3-4c323812d02f.png)

**Comment by tawalaya** [comment]
That is expected behavior, the `@timestamp` is the point in time when the message was received by the agent, the one in `value` is what ever the client decided to put there, its just a string. The last timestamp is deprecated and only there for backwards compatibility. 

The date difference could be due to out of sync clocks in the agent and client.
